version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - ineffassign
    - misspell
    - bodyclose
    - gosec

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
